# Generated by Django 2.1.7 on 2019-03-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pods_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=64)),
                ('namespace', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
            ],
        ),
    ]
