# Generated by Django 2.1.7 on 2019-03-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20190315_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='namespace_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='pvs_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('capacity', models.CharField(max_length=64)),
                ('access_modes', models.CharField(max_length=64)),
                ('persistent_volume_reclaim_policy', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('storage_class_name', models.CharField(max_length=64)),
            ],
        ),
    ]
