# Generated by Django 2.1.7 on 2019-03-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_pvc_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='svc_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('namespace', models.CharField(max_length=64)),
                ('cluster_ip', models.CharField(max_length=64, null=True)),
                ('node_port', models.CharField(max_length=64, null=True)),
                ('port', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
